remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - "Вивід - функція print.md"
  - Типи%20значень%20-%20рядки,%20цілі%20та%20дійсні%20числа.md
  - Зміні%20-%20присвоєння%20значень.md
